### PR TITLE
Added iphone x package helper

### PR DESCRIPTION
**Pull request by rollsroyc3**
This takes care of the XR issue and any other iPhone X related height changes in the future so this package can just focus on the flash message.

### CODE REVIEW

**Comment by lucasferreira** [comment]
Hi @rollsroyc3,

Thank you very much for this contrib!

Did you test in emulators both iPhone XS and XR?

What do you think about "safe" parameter that `getStatusBarHeight` function from @react-native-iphone-x-helper package indicartes tu use when you need extra top padding?

Look externally and without testing (sorry for now) I think that we could need this "safe" parameter to asure 44 pixels of padding height.

**Comment by lucasferreira** [comment]
Hi @rollsroyc3,

I don't know if you still work on this (and thank you again) but can I explain why you change the OFFSET_HEIGHT? Did you found some bug also on Android devices?

**Comment by rollsroyc3** [comment]
> Hi @rollsroyc3,
> 
> Thank you very much for this contrib!
> 
> Did you test in emulators both iPhone XS and XR?
> 
> What do you think about "safe" parameter that `getStatusBarHeight` function from @react-native-iphone-x-helper package indicartes tu use when you need extra top padding?
> 
> Look externally and without testing (sorry for now) I think that we could need this "safe" parameter to asure 44 pixels of padding height.

Yes, looks good in both iPhone XS and XR for me.

For some reason it didn't match up with my header on Android, so you might want to test this branch on a few other devices to confirm but it now looks good on my S8.

As for the getStatusBarHeight safe param, its not needed because I'm only using it for non iPhone X devices.

> isIphoneX() ? 90 : 90 - getStatusBarHeight();

And this will always return 20 as stated here:

> the height of the status bar: 44 for safe iPhoneX, 30 for unsafe iPhoneX, 20 for other iOS devices and StatusBar.currentHeight for Android.

**Comment by lucasferreira** [comment]
Thank you very much @rollsroyc3 

I've merged you PR, and before a few adjustments by myself now we have the proper "notch" support!

**Pull request merged**
